# permissions for end users to view keycloakcomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakcomponent-viewer-role
rules:
- apiGroups:
  - config.idp.edenlab.io
  resources:
  - keycloakcomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.idp.edenlab.io
  resources:
  - keycloakcomponents/status
  verbs:
  - get
