# Organization with identity provider configuration
apiVersion: config.idp.edenlab.io/v1alpha1
kind: KeycloakOrganization
metadata:
  name: test-keycloak-organization
  namespace: keycloak
  annotations:
    # skip resource delete
    "idp.edenlab.io/preserve-resources-no-delete": "true"
spec:
  # RealmRef is reference to Realm custom resource.
  realmRef:
    # Kind specifies the kind of the Keycloak resource.
    #
    # Default: KeycloakRealm
    kind: KeycloakRealm

    # Name specifies the name of the Keycloak resource.
    name: ksa-ehealth

  # Configuration to Keycloak cluster
  configRef:
    # Secret is a secret name which contains admin credentials.
    secret: keycloak-ksa-ehealth-access

    # URL of keycloak service.
    url: "http://keycloak:8080"

  # Name is the unique name of the organization. The name should be unique across Organizations.
  name: "Test Organization"

  # Alias is the unique alias for the organization. The alias should be unique across Organizations. Alias is immutable after creation.
  #
  # Validations:
  # self == oldSelf: alias is immutable
  alias: "test-org"

  # Domains is a list of email domains associated with the organization. Each domain should be unique across Organizations.
  domains:
    - "example.com"
    - "test.com"

  # RedirectURL is the optional redirect URL for the organization.
  redirectUrl: "https://example.com/redirect"

  # Description is an optional description of the organization.
  description: "Test organization"

  # Attributes is a map of custom attributes for the organization.
  attributes:
    department:
      - "engineering"
      - "qa"
    location:
      - "us-east"

  # IdentityProviders is a list of identity providers associated with the organization.
  # One identity provider can't be assigned to multiple organizations.
  identityProviders:
      # Alias is the unique identifier for the identity provider within the organization.
    - alias: "test-org-idp"
